// Pack template per PLAN_EN.md §9.5 (v2.7). The output is plain Markdown the user pastes
// into a chat tool, email, or document. The instruction header is in English on purpose
// (§19.13: receiving AIs follow English instructions — especially negative constraints
// and edge-case rules — more reliably than Chinese ones); the user's own content stays in
// its original language, and the closing directive asks for output in the user's language.

// --- Whitespace / indentation -----------------------------------------------------------
// Centralised so the sub-line layout (notes, attachments, extracted text) is easy to tweak.
export const NOTE_INDENT = '    '; // 4 spaces — annotation + attachment marker lines
export const EXTRACT_INDENT = '      '; // 6 spaces — extracted file-text body
export const PINNED_PREFIX = '📌 '; // prepended to a pinned block's time bracket
export const EXTRACT_CHAR_CAP = 8000; // max extracted chars inlined per attachment

// --- Inline markers ---------------------------------------------------------------------
export const SOURCE_MARKER = ' · from ';
export const NOTE_MARKER = 'note: ';
export const FILE_MARKER = '↳ attached file: ';
export const FOLDER_MARKER = '↳ attached folder: ';
export const URL_MARKER = '↳ attached URL: ';
export const REF_MARKER = '→ Referenced thread: ';
export const ATTACHMENT_SEE_BELOW = ' — see Related Files & Links section below';

// --- Section headings -------------------------------------------------------------------
export const SECTION_PINNED = '## Pinned Blocks';
export const SECTION_LOG = '## Full Record (chronological)';
export const SECTION_FILES = '## Related Files & Links';

export const EMPTY_PINNED_LINE = '(no pinned blocks)';
export const EMPTY_LOG_LINE = '(no blocks yet)';
export const UNKNOWN_THREAD = '(unknown thread)';

// --- Top of the pack --------------------------------------------------------------------
export const PACK_HEADER = (title: string, dateStr: string, blockCount: number): string =>
  `# Project Context: ${title || '(untitled)'}\n\n` +
  `Generated by Spool on ${dateStr}. ${blockCount} blocks total.`;

// --- The four-category instruction header (verbatim — §9.5 / §19.13) --------------------
// This static text teaches the receiving AI how to weigh the blocks below. It is core IP:
// do not reword it. It opens and closes with a `---` rule so it reads as its own section.
export const INSTRUCTION_HEADER = `---

## How to Read This Context

The blocks below come from FOUR different authority categories. Treat each
category according to the rules in this section. This sorting matters —
mishandling categories will produce wrong or unsafe output.

### 📖 Reference (authoritative)
Blocks whose \`source\` looks like an institutional / official artifact:
- email clients (Mail, Outlook, etc.)
- school / institutional domains
- file attachments (PDF, docx, slides)
- forum / platform posts from authoritative figures

**Handling**: Treat as ground truth. Do not contradict. Do not extrapolate
beyond what they say. If they conflict with other categories, Reference wins.

### 🧩 Synthesis (already-formed understanding)
Blocks whose \`source\` is another AI tool (Claude, ChatGPT, Gemini, etc.)
AND whose content has the shape of a long structured explanation (headings,
formulas, multi-paragraph essays).

**Handling**: These are someone else's synthesis. They may be useful as
background or framing, but their correctness is not guaranteed. Do not
treat them as facts. If they contradict Reference, defer to Reference.
Do not copy them wholesale into your output.

### 🔄 Process (conversation traces — read for evolution, not facts)
Blocks whose \`source\` is another AI tool AND whose content has the shape
of a question-and-answer dialogue (multiple turns, short exchanges,
dialogue markers like "User:" or "Q:" or "我:", high question density).

**Handling**: The literal content of these blocks is NOT a reliable source
of facts. What IS reliable is the user's evolving questions — what they
ask repeatedly, where they got confused, what they kept circling back to.
Extract these as signals of the user's cognitive gaps and address them,
but never quote the AI responses inside these blocks as if they were
authoritative.

### 💭 Personal (the user's own hypotheses and notes)
Blocks with no \`source\` field — these are typed by the user directly
into Spool. They represent the user's current understanding, often
incomplete or speculative.

**Handling**: Read these to understand where the user currently stands.
If they contain factual errors, point them out directly — do not protect
the user's feelings at the cost of correctness.

---`;

// --- Closing language directive (verbatim — §9.5) ---------------------------------------
export const OUTPUT_LANGUAGE = `## Output Language

Respond in Simplified Chinese unless content itself dictates otherwise
(e.g. don't translate quoted English source material). Technical terms
may stay in their original language.`;

// --- Truncation marker for over-long extracted text -------------------------------------
export const truncationMarker = (remainder: number): string =>
  `[... truncated, ${remainder} more chars not shown ...]`;
