// Pack template per PLAN_EN.md §9.5 (v2.7). The output is plain Markdown the user pastes
// into a chat tool, email, or document. The instruction header is in English on purpose
// (§19.13: receiving AIs follow English instructions — especially negative constraints
// and edge-case rules — more reliably than Chinese ones); the user's own content stays in
// its original language, and the closing directive asks for output in the user's language.

// --- Whitespace / indentation -----------------------------------------------------------
// Centralised so the sub-line layout (notes, attachments, extracted text) is easy to tweak.
export const NOTE_INDENT = '    '; // 4 spaces — annotation + attachment marker lines
export const EXTRACT_INDENT = '      '; // 6 spaces — extracted file-text body
export const PINNED_PREFIX = '📌 '; // prepended to a pinned block's time bracket
export const EXTRACT_CHAR_CAP = 8000; // max extracted chars inlined per attachment

// --- Inline markers ---------------------------------------------------------------------
export const SOURCE_MARKER = ' · from ';
export const NOTE_MARKER = 'note: ';
export const FILE_MARKER = '↳ attached file: ';
export const FOLDER_MARKER = '↳ attached folder: ';
export const URL_MARKER = '↳ attached URL: ';
export const REF_MARKER = '→ Referenced project: ';
// v2.4 (§20.13 D2): block-level citation sub-line — "this block builds on that one".
// English like every other pack marker (§19.13). The preview keeps the receiving AI
// from needing another lookup; a deleted citee renders the MISSING text instead.
export const REF_BLOCK_MARKER = '↩ cites: ';
export const REF_BLOCK_MISSING = '(cited block no longer exists)';
export const ATTACHMENT_SEE_BELOW = ' — see Related Files & Links section below';

// --- Section headings -------------------------------------------------------------------
export const SECTION_PINNED = '## Pinned Blocks';
export const SECTION_LOG = '## Full Record (chronological)';
export const SECTION_FILES = '## Related Files & Links';

export const EMPTY_PINNED_LINE = '(no pinned blocks)';
export const EMPTY_LOG_LINE = '(no blocks yet)';
export const UNKNOWN_THREAD = '(unknown project)';
// 2026-07-09: pinned blocks render in full ONLY in the Pinned Blocks section; their
// Full Record slot is this one-line placeholder (they were duplicated verbatim before,
// inflating large packs by the size of every pinned block).
export const PINNED_SEE_ABOVE = '(pinned — full text in "Pinned Blocks" above)';

// --- Top of the pack --------------------------------------------------------------------
// `scope` is set when the block list was narrowed by a range selector: the count line then
// says how many of the project's blocks this pack holds. Without it the pack claimed
// "3 blocks total" for a last7 slice of a 17-block project, and whoever it was pasted to
// believed the project had three blocks (MCP field review 2026-08-04, B-3).
export const PACK_HEADER = (
  title: string,
  dateStr: string,
  blockCount: number,
  scope?: { range: string; total: number },
): string =>
  `# Project Context: ${title || '(untitled)'}\n\n` +
  `Generated by Spool on ${dateStr}. ` +
  (scope
    ? `${blockCount} of ${scope.total} blocks in this project ` +
      `(range: ${scope.range} — ${RANGE_REST[scope.range] ?? RANGE_REST.last7}, still in Spool).`
    : `${blockCount} blocks total.`);

// Why the rest are missing depends on which range asked for them: `pinned` is not a time
// window, so the time-window wording said something false about the other blocks (MCP
// review round 2, 2026-08-04).
const RANGE_REST: Record<string, string> = {
  pinned: 'the rest are not pinned',
  last7: 'the rest are older than this window',
  last30: 'the rest are older than this window',
};

// --- The four-category instruction header (verbatim — §9.5 / §19.13) --------------------
// This static text teaches the receiving AI how to weigh the blocks below. It is core IP:
// do not reword it. It opens and closes with a `---` rule so it reads as its own section.
export const INSTRUCTION_HEADER = `---

## How to Read This Context

The blocks below come from FOUR different authority categories. Treat each
category according to the rules in this section. This sorting matters —
mishandling categories will produce wrong or unsafe output.

### 📖 Reference (authoritative)
Blocks whose \`source\` looks like an institutional / official artifact:
- email clients (Mail, Outlook, etc.)
- school / institutional domains
- file attachments (PDF, docx, slides)
- forum / platform posts from authoritative figures

**Handling**: Treat as ground truth. Do not contradict. Do not extrapolate
beyond what they say. If they conflict with other categories, Reference wins.

### 🧩 Synthesis (already-formed understanding)
Blocks whose \`source\` is another AI tool (Claude, ChatGPT, Gemini, etc.)
AND whose content has the shape of a long structured explanation (headings,
formulas, multi-paragraph essays).

**Handling**: These are someone else's synthesis. They may be useful as
background or framing, but their correctness is not guaranteed. Do not
treat them as facts. If they contradict Reference, defer to Reference.
Do not copy them wholesale into your output.

### 🔄 Process (conversation traces — read for evolution, not facts)
Blocks whose \`source\` is another AI tool AND whose content has the shape
of a question-and-answer dialogue (multiple turns, short exchanges,
dialogue markers like "User:" or "Q:" or "我:", high question density).

**Handling**: The literal content of these blocks is NOT a reliable source
of facts. What IS reliable is the user's evolving questions — what they
ask repeatedly, where they got confused, what they kept circling back to.
Extract these as signals of the user's cognitive gaps and address them,
but never quote the AI responses inside these blocks as if they were
authoritative.

### 💭 Personal (the user's own hypotheses and notes)
Blocks with no \`source\` field — these are typed by the user directly
into Spool. They represent the user's current understanding, often
incomplete or speculative.

**Handling**: Read these to understand where the user currently stands.
If they contain factual errors, point them out directly — do not protect
the user's feelings at the cost of correctness.

### ⭐ User-highlighted spans (\`==…==\`)
Substrings wrapped in \`==…==\` inside any block above are sentence-level key points the user emphasized at capture time — prioritize them. They coexist with pinned blocks (pin = whole block is core context; highlight = a sentence within a block is key); when a highlight sits inside a pinned block, treat it as one emphasis, not two.

---`;

// --- Closing language directive (verbatim — §9.5) ---------------------------------------
// 2026-08-04 (Ocean): this used to hard-code Simplified Chinese in every pack, in every
// locale — an English user with an English app pasted a pack and got answered in Chinese.
// It now follows Spool's UI language. The rest of the pack skeleton stays English on
// purpose (§19.13: receiving AIs follow English instructions more reliably); this one
// directive is different, because it is the only line whose whole job is to decide what
// language the USER is answered in.
export const OUTPUT_LANGUAGE_BY_LANG = {
  zh: `## Output Language

Respond in Simplified Chinese unless content itself dictates otherwise
(e.g. don't translate quoted English source material). Technical terms
may stay in their original language.`,
  en: `## Output Language

Respond in English unless content itself dictates otherwise
(e.g. don't translate quoted source material). Technical terms
may stay in their original language.`,
} as const;

export const OUTPUT_LANGUAGE = OUTPUT_LANGUAGE_BY_LANG.zh;

// --- Truncation marker for over-long extracted text -------------------------------------
export const truncationMarker = (remainder: number): string =>
  `[... truncated, ${remainder} more chars not shown ...]`;

// --- Pack task templates (v2.8 §20.7, Experimental Track B) -----------------------------
// Orthogonal to the four-category authority header: that header says HOW TO READ the
// input, a template says WHAT TASK to perform. A template is just a different closing
// instruction block appended after "Related Files & Links", before the Output Language
// line — the header + block bodies are byte-identical across templates. Hardcoded set,
// no editor, no per-thread persistence; intent is to learn from dogfooding which (if
// any) earn their place, not to build a system. Default = `default` (no extra block —
// preserves pre-v2.8 behavior).
//
// Instruction text is English on purpose (§19.13: LLMs follow English directives more
// reliably for negative constraints + edge-case rules). Each block opens with `## Task`
// so the receiving AI lands cleanly on the instruction the user wants it to perform.

export type PackTemplateKey = 'default' | 'revision' | 'combine';

export const PACK_TEMPLATE_KEYS: PackTemplateKey[] = ['default', 'revision', 'combine'];

export interface PackTemplate {
  key: PackTemplateKey;
  // UI label shown in the PackDialog selector. Chinese — this is the only user-facing
  // template metadata; the body is what the receiving AI reads (English).
  label: string;
  // Tooltip / hint shown beside the selector.
  hint: string;
  // The closing block appended after "Related Files & Links" and before "## Output
  // Language". `null` = no extra block (the `default` template).
  closing: string | null;
}

const REVISION_CLOSING = `## Task

Generate revision materials from the context above, respecting the four-category authority hierarchy:
- Use 📖 Reference content as ground truth.
- Treat 🧩 Synthesis as framing only; do not copy it wholesale.
- Mine 🔄 Process traces for the user's recurring confusions and turn them into review prompts.
- Validate 💭 Personal hypotheses against Reference; correct factual errors directly.

Produce: (1) a short summary of the core ideas the user should master, (2) a focused list of question-and-answer review items targeting the user's apparent gaps, and (3) one or two open-ended prompts the user can use to self-test.`;

const COMBINE_CLOSING = `## Task

The blocks above are scattered fragments — multiple captures from chats, notes, and references that overlap and partly repeat. Synthesize them into ONE clean, deduplicated summary that:
- Preserves the four-category authority hierarchy (📖 Reference wins over 🧩 Synthesis wins over 🔄 Process; 💭 Personal is the user's current model, possibly wrong).
- Collapses repetition and resolves contradictions explicitly (state which source each retained claim came from).
- Reads as one coherent document, not a list of fragments.

Do not invent content beyond what the blocks provide. If a claim cannot be supported by the blocks, omit it or call it out as a gap.`;

export const PACK_TEMPLATES: Record<PackTemplateKey, PackTemplate> = {
  default: {
    key: 'default',
    label: '纯上下文',
    hint: '只交付上下文，不附加任务（当前默认）',
    closing: null,
  },
  revision: {
    key: 'revision',
    label: '复习资料',
    hint: '让 AI 据此生成复习材料',
    closing: REVISION_CLOSING,
  },
  combine: {
    key: 'combine',
    label: '组合零散对话',
    hint: '把碎片整合成一份去重的干净总结',
    closing: COMBINE_CLOSING,
  },
};

export const DEFAULT_PACK_TEMPLATE: PackTemplateKey = 'default';
