/* Builds site/zh/*.html from the English pages plus scripts/site-zh-strings.mjs.
 *
 * The English HTML is the only hand-written page source: every visitor-facing
 * string carries a data-i18n key, and this script swaps each one for its Chinese
 * line. Nothing here is clever — it walks the tag it found the attribute on,
 * replaces that element's contents, and rewrites the handful of relative links
 * that change meaning one directory down.
 *
 * Run it after editing site/index.html, site/privacy.html or the Chinese copy:
 *
 *     node scripts/build-site-zh.mjs
 *
 * The output is committed, so what deploys is visible in git. A vitest case
 * (build-site-zh.test.mjs) regenerates and compares, so a forgotten run turns
 * the suite red instead of silently shipping a stale translation.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { ZH, HEAD } from './site-zh-strings.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = join(ROOT, 'site');

const BANNER =
  '<!-- Generated by scripts/build-site-zh.mjs from the English page and\n' +
  '     scripts/site-zh-strings.mjs. Do not edit — edit those and re-run. -->';

/* The nav toggle is a plain link now, and it doubles as the map back to the
   other language: assets/lang.js reads its href to forward old ?lang= links. */
const TOGGLE = {
  'index.html': '<a class="lang-toggle" href="../" hreflang="en" lang="en">EN</a>',
  'privacy.html': '<a class="lang-toggle" href="../privacy.html" hreflang="en" lang="en">EN</a>',
};

/* End of the element whose opening tag ends at `from`, counting nested tags of
   the same name so a <div> inside a <div> does not close it early. */
function endOfElement(html, tag, from) {
  const open = new RegExp(`<${tag}\\b`, 'gi');
  const close = new RegExp(`</${tag}\\s*>`, 'gi');
  let depth = 1;
  let i = from;
  while (depth > 0) {
    open.lastIndex = i;
    close.lastIndex = i;
    const o = open.exec(html);
    const c = close.exec(html);
    if (!c) throw new Error(`unclosed <${tag}> at ${from}`);
    if (o && o.index < c.index) {
      depth += 1;
      i = o.index + o[0].length;
    } else {
      depth -= 1;
      if (depth === 0) return c.index;
      i = c.index + c[0].length;
    }
  }
  throw new Error('unreachable');
}

function applyStrings(html, used) {
  const tagged = /<([a-z0-9]+)\b[^>]*\bdata-i18n="([^"]+)"[^>]*>/gi;
  let out = '';
  let cursor = 0;
  let m;
  while ((m = tagged.exec(html)) !== null) {
    const [full, tag, key] = m;
    if (!(key in ZH)) throw new Error(`no Chinese for data-i18n="${key}"`);
    used.add(key);
    const inner = m.index + full.length;
    const end = endOfElement(html, tag, inner);
    out += html.slice(cursor, inner) + ZH[key];
    cursor = end;
    tagged.lastIndex = end;
  }
  return out + html.slice(cursor);
}

/* Meaningful image descriptions are attributes, not element contents. Keep
   this one case explicit so the generator does not turn into a general-purpose
   HTML rewriter. */
function applyAltStrings(html, used) {
  const tagged = /<img\b[^>]*\bdata-i18n-alt="([^"]+)"[^>]*>/gi;
  return html.replace(tagged, (full, key) => {
    if (!(key in ZH)) throw new Error(`no Chinese for data-i18n-alt="${key}"`);
    const attr = /\salt="[^"]*"/;
    if (!attr.test(full)) throw new Error(`data-i18n-alt="${key}" has no alt attribute`);
    used.add(key);
    const value = ZH[key]
      .replaceAll('&', '&amp;')
      .replaceAll('"', '&quot;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;');
    return full.replace(attr, ` alt="${value}"`);
  });
}

/* The logo animation also conveys meaning, so its accessible name follows the
   page language just like image alt text. Keep the supported attribute narrow
   and explicit rather than turning this builder into a general HTML parser. */
function applyAriaStrings(html, used) {
  const tagged = /<([a-z0-9]+)\b[^>]*\bdata-i18n-aria="([^"]+)"[^>]*>/gi;
  return html.replace(tagged, (full, _tag, key) => {
    if (!(key in ZH)) throw new Error(`no Chinese for data-i18n-aria="${key}"`);
    const attr = /\saria-label="[^"]*"/;
    if (!attr.test(full)) throw new Error(`data-i18n-aria="${key}" has no aria-label attribute`);
    used.add(key);
    const value = ZH[key]
      .replaceAll('&', '&amp;')
      .replaceAll('"', '&quot;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;');
    return full.replace(attr, ` aria-label="${value}"`);
  });
}

function escapeAttribute(value) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('"', '&quot;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');
}

/* Swap the whole element marked data-zh-body for a hand-written Chinese
   fragment. Only the privacy policy needs this: its Chinese text is the
   authoritative version and is written as Chinese, not keyed phrase by phrase. */
function applyBody(html, page) {
  const marked = /<([a-z0-9]+)\b[^>]*\bdata-zh-body="([^"]+)"[^>]*>/i.exec(html);
  if (!marked) return html;
  const [full, tag, name] = marked;
  const inner = marked.index + full.length;
  const end = endOfElement(html, tag, inner);
  const fragment = readFileSync(join(ROOT, 'scripts', `site-zh-${name}.html`), 'utf8');
  if (!fragment.trim()) throw new Error(`empty Chinese body for ${page}`);
  return html.slice(0, inner) + '\n' + fragment.trim() + '\n' + html.slice(end);
}

function replaceOnce(html, pattern, replacement, what) {
  const hits = html.match(pattern);
  if (!hits || hits.length !== 1) {
    throw new Error(`expected exactly one ${what}, found ${hits ? hits.length : 0}`);
  }
  return html.replace(pattern, () => replacement);
}

function applyHead(html, page) {
  const head = HEAD[page];
  let out = replaceOnce(html, /<html lang="en">/, '<html lang="zh-CN">', '<html lang>');
  out = replaceOnce(out, /<title>[^<]*<\/title>/, `<title>${head.title}</title>`, '<title>');
  out = replaceOnce(
    out,
    /<meta name="description" content="[^"]*">/,
    `<meta name="description" content="${escapeAttribute(head.description)}">`,
    'meta description',
  );
  out = replaceOnce(
    out,
    /<link rel="canonical" href="[^"]*">/,
    `<link rel="canonical" href="https://spoolapp.org/zh/${page === 'index.html' ? '' : page}">`,
    'canonical link',
  );
  /* pages without social cards (privacy) stop here */
  if (!head.ogTitle) return out;
  const social = [
    [/<meta property="og:url" content="[^"]*">/, `<meta property="og:url" content="https://spoolapp.org/zh/">`],
    [/<meta property="og:title" content="[^"]*">/, `<meta property="og:title" content="${escapeAttribute(head.ogTitle)}">`],
    [/<meta property="og:description" content="[^"]*">/, `<meta property="og:description" content="${escapeAttribute(head.ogDescription)}">`],
    [/<meta property="og:image:alt" content="[^"]*">/, `<meta property="og:image:alt" content="${escapeAttribute(head.ogImageAlt)}">`],
    [/<meta property="og:locale" content="[^"]*">/, `<meta property="og:locale" content="zh_CN">`],
    [/<meta property="og:locale:alternate" content="[^"]*">/, `<meta property="og:locale:alternate" content="en">`],
    [/<meta name="twitter:title" content="[^"]*">/, `<meta name="twitter:title" content="${escapeAttribute(head.ogTitle)}">`],
    [/<meta name="twitter:description" content="[^"]*">/, `<meta name="twitter:description" content="${escapeAttribute(head.ogDescription)}">`],
  ];
  for (const [pattern, replacement] of social) {
    out = replaceOnce(out, pattern, replacement, `${pattern}`);
  }
  return out;
}

/* One directory down, so shared assets and the English-only story page need to
   climb back out. Everything else (./ , #anchors, privacy.html, absolute URLs)
   already means the right thing inside /zh/. A srcset lists several paths in one
   attribute, so the match has to allow a comma before the path, not just the
   opening quote. */
function applyPaths(html) {
  const relative = /(["]|,\s*)assets\//g;
  const out = html.replace(relative, '$1../assets/').replaceAll('"story.html"', '"../story.html"');
  /* absolute https://spoolapp.org/assets/… URLs are left alone on purpose, so
     only re-check the shapes that were meant to be rewritten */
  const missed = out.match(relative);
  if (missed) throw new Error(`${missed.length} asset path(s) not rewritten for /zh/`);
  return out;
}

export function renderZh(page) {
  const src = readFileSync(join(SITE, page), 'utf8');
  const used = new Set();
  let out = applyBody(src, page);
  out = applyStrings(out, used);
  out = applyAltStrings(out, used);
  out = applyAriaStrings(out, used);
  out = applyHead(out, page);
  out = applyPaths(out);
  out = replaceOnce(out, /<a class="lang-toggle"[^>]*>[^<]*<\/a>/, TOGGLE[page], 'language toggle');
  out = out.replace('<!doctype html>', `<!doctype html>\n${BANNER}`);
  return { html: out, used };
}

export const PAGES = Object.keys(HEAD);

export function renderAll() {
  const used = new Set();
  const pages = {};
  for (const page of PAGES) {
    const r = renderZh(page);
    pages[page] = r.html;
    r.used.forEach((k) => used.add(k));
  }
  const unused = Object.keys(ZH).filter((k) => !used.has(k));
  return { pages, unused };
}

/* CLI */
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { pages, unused } = renderAll();
  mkdirSync(join(SITE, 'zh'), { recursive: true });
  for (const [page, html] of Object.entries(pages)) {
    writeFileSync(join(SITE, 'zh', page), html);
    console.log(`site/zh/${page}  ${html.length} bytes`);
  }
  if (unused.length) console.log(`\nunused Chinese keys: ${unused.join(', ')}`);
}
