import { describe, expect, it } from 'vitest';
import { auditEntry, compareByEntry, entryPercent, splitPackEntries } from './compressBlocks';

// 一份最小的 pack，形状和真的一样：小节标题、💭 记号、方括号里的时间和来源、缩进的批注行。
const PACK = `# Project Context: 宣发

Generated by Spool on 2026-08-21. 3 blocks total.

## Pinned Blocks

📌 #1 [2026-08-01 09:00 · from Safari] 报名截止 2026-03-15。
    💭 note: 这条是硬要求

## Full Record (chronological)

#2 [2026-08-20 13:50 · from Claude] 一段很长的引文，里面有 ==划出来的重点== 和别的话。
第二行也属于这一块。
💭 #3 [2026-08-20 14:00] 我自己写的一句。

## Output Language

Answer in Chinese.`;

describe('splitPackEntries', () => {
  it('把 pack 切成条目，记号、时间、来源、正文各归各位', () => {
    const es = splitPackEntries(PACK);
    expect(es.map((e) => e.seq)).toEqual([1, 2, 3]);
    expect(es[0].marks).toEqual(['📌']);
    expect(es[0].section).toBe('Pinned Blocks');
    expect(es[0].source).toBe('Safari');
    expect(es[0].time).toBe('2026-08-01 09:00');
    // 缩进的批注行属于它上面那一块，不是下一块的开头。
    expect(es[0].raw).toContain('note: 这条是硬要求');
    // 没有 `· from` = 用户自己写的，pack 上印的就是 💭。
    expect(es[2].source).toBeNull();
    expect(es[2].marks).toEqual(['💭']);
  });

  it('续行归到它所属的那一块', () => {
    const es = splitPackEntries(PACK);
    expect(es[1].body).toContain('第二行也属于这一块');
    expect(es[2].body).not.toContain('第二行');
  });

  it('小节标题结束一块 —— Output Language 不会被吸进最后一条', () => {
    const es = splitPackEntries(PACK);
    expect(es[2].raw).not.toContain('Answer in Chinese');
  });
});

describe('compareByEntry', () => {
  it('按 #N 配对，一块对一块', () => {
    const c = compareByEntry(PACK, PACK);
    expect(c).not.toBeNull();
    expect(c!.pairs.map((p) => p.seq)).toEqual([1, 2, 3]);
    expect(c!.dropped).toBe(0);
    expect(c!.invented).toBe(0);
    expect(entryPercent(c!.pairs[0])).toBe(100);
  });

  // ⚠️ §9.6.5 点名的那条：模型漏了一块，必须显示「第 N 块在压缩稿里找不到」，不许静默跳过。
  it('压缩稿里少了一块，那一对留着，右边是空的', () => {
    const short = PACK.split('\n').filter((l) => !l.startsWith('💭 #3')).join('\n');
    const c = compareByEntry(PACK, short)!;
    expect(c.dropped).toBe(1);
    const gone = c.pairs.find((p) => p.seq === 3)!;
    expect(gone.before).not.toBeNull();
    expect(gone.after).toBeNull();
  });

  // 反过来也要看得见：它编了一个原文没有的编号。
  it('压缩稿凭空多出来一个编号，也列出来', () => {
    const more = PACK + '\n#9 [2026-08-20 15:00 · from Claude] 原文里没有这一块。';
    const c = compareByEntry(PACK, more)!;
    expect(c.invented).toBe(1);
    expect(c.pairs.find((p) => p.seq === 9)!.before).toBeNull();
  });

  // ⛔ 实测第 7 次撞见的那个：它把整份 pack 原样写了两遍（22 块 → 44 块，剩 194%）。
  // 只按 #N 配对的话这看起来一对不缺，而用户拿到的是一份两倍长的东西。
  it('压缩稿里同一个编号出现两次，单独报出来', () => {
    const twice = PACK + '\n' + PACK;
    const c = compareByEntry(PACK, twice)!;
    expect(c.duplicated).toEqual([1, 2, 3]);
    expect(c.after).toBe(6);
    expect(c.dropped).toBe(0);
    expect(c.invented).toBe(0);
  });

  // ⛔ 置顶的块在 pack 里本来就出现两次（Pinned Blocks 里全文 + Full Record 里一行占位）。
  // 只按 #N 配对会把每一个有置顶块的项目都报成「写了两遍」——实测在〈Flux〉上撞见过。
  it('置顶块的两次出现不算重复', () => {
    const c = compareByEntry(PACK, PACK)!;
    expect(c.duplicated).toEqual([]);
    // 两次出现各自配对：Pinned Blocks 里那一条，和 Full Record 里那一条。
    expect(c.pairs.filter((p) => p.seq === 1)).toHaveLength(1);
    expect(c.pairs[0].section).toBe('Pinned Blocks');
  });

  // 「解析失败必须是一个可见的结果，不是一个异常」——所以返回 null，界面据此退回整份对照。
  it('压缩稿一条都切不出来时返回 null，而不是抛异常', () => {
    expect(compareByEntry(PACK, '模型没照格式写，整段散文。')).toBeNull();
  });
});

// ⛔ 实测撞见的截断（2026-08-21，〈Flux〉#3 是一份 README）：块正文里本来就有二级标题。
describe('正文里的 ## 标题不是小节边界', () => {
  const WITH_MD = [
    '## Full Record (chronological)',
    '#1 [t · from Code] # FLUX',
    '',
    '## 研究线',
    'uv + Python 3.12 可复现环境。',
    '',
    '## 变换层',
    '六种变换。',
    '#2 [t · from Code] 下一块。',
    '## Output Language',
    'Answer in Chinese.',
  ].join('\n');

  it('一块正文里的 ## 归这一块，不截断', () => {
    const es = splitPackEntries(WITH_MD);
    expect(es.map((e) => e.seq)).toEqual([1, 2]);
    expect(es[0].body).toContain('## 研究线');
    expect(es[0].body).toContain('六种变换');
    expect(es[0].section).toBe('Full Record (chronological)');
  });

  it('pack 自己的小节标题照旧是边界', () => {
    const es = splitPackEntries(WITH_MD);
    expect(es[1].raw).not.toContain('Answer in Chinese');
  });
});

// ⛔ 实测撞见的静默丢块（2026-08-21，〈Flux〉#5 是从 Microsoft Word 粘进来的）：
// 那一块的行尾带 `\r`，而 JS 的 `.` 不匹配 `\r`，头行于是解析不出来 —— 旧代码 `continue`
// 掉了它，**不报错、不提示，那一块就是不在核对面上**。
describe('从 Word 粘过来的块（CRLF）不会消失', () => {
  const CRLF = [
    '## Full Record (chronological)',
    '#5 [2026-08-05 15:09 · from Microsoft Word] Experience 2\r',
    'Sound design for a short film.\r',
    '    💭 note: 这段要留着\r',
    '#6 [2026-08-06 14:16 · from Claude · MCP] 下一块。',
  ].join('\n');

  it('照样切得出来', () => {
    expect(splitPackEntries(CRLF).map((e) => e.seq)).toEqual([5, 6]);
  });

  it('批注也认得出来 —— 少了要报', () => {
    const cut = CRLF.split('\n').filter((l) => !l.includes('note:')).join('\n');
    expect(compareByEntry(CRLF, cut)!.pairs[0].audit.missingNotes).toEqual(['这段要留着']);
  });
});

describe('auditEntry', () => {
  it('少掉的批注和高亮，指到具体那一块', () => {
    const [pinned, quoted] = splitPackEntries(PACK);
    expect(auditEntry(pinned, { ...pinned, raw: '📌 #1 [x] 报名截止 2026-03-15。' }).missingNotes)
      .toEqual(['这条是硬要求']);
    expect(auditEntry(quoted, { ...quoted, raw: '#2 [x] 一段引文。' }).missingHighlights)
      .toEqual(['划出来的重点']);
  });

  // 防「添」：压缩稿里的批注行，原文那一块里没有同样的一行。
  it('凭空多写的批注，按块指出来', () => {
    const [pinned] = splitPackEntries(PACK);
    const forged = { ...pinned, raw: pinned.raw + '\n    ↪ note: 我没写过这句' };
    expect(auditEntry(pinned, forged).fabricatedNotes).toEqual(['我没写过这句']);
  });
});
