import { describe, expect, it } from 'vitest';
import {
  auditCompression,
  auditHasLosses,
  countPackEntries,
  diffChunks,
  diffLines,
  estimateCost,
  formatYuan,
  isPeakBeijing,
  measurementRecord,
  mergeOutcomes,
  numbersGateOpen,
  overlapRatio,
  pairRewrites,
  priceTier,
  type CompressOutcome,
} from './compress';

const ORIGINAL = `# Project Context: 机器学习课

Generated by Spool on 2026-08-20. 4 blocks total.

## How to Read This Context

四带说明……

## Full Record (chronological)

📌 #1 [2025-05-06 15:00 · from Claude] 一直没懂为什么要除 sqrt(d_k)
#2 [2025-06-05 06:06 · from Safari] 课程要求:期末项目要复现一篇 ==2024 年后== 的论文
    💭 note: 这条是硬要求,别忘了
💭 #3 [2025-06-15 15:06] 我的想法:先复现 baseline 再谈改进
#4 [2025-06-15 15:16 · from Claude] 结论:除以 sqrt(d_k) 控制点积方差

## Output Language

Answer in Chinese.`;

const outcome = (over: Partial<CompressOutcome> = {}): CompressOutcome => ({
  ok: true,
  text: '',
  cuts: null,
  kind: null,
  message: null,
  status: null,
  inputTokens: 30_000,
  outputTokens: 2_000,
  cachedInputTokens: null,
  reasoningTokens: null,
  ms: 8_000,
  model: 'deepseek-v4-flash',
  ...over,
});

describe('数块', () => {
  it('数的是条目行，不是所有行', () => {
    expect(countPackEntries(ORIGINAL)).toBe(4);
  });

  it('📌 和 💭 前缀不影响计数', () => {
    expect(countPackEntries('📌 #1 [a] x\n💭 #2 [b] y\n#3 [c] z')).toBe(3);
  });
});

describe('核对：不该删的删了没有', () => {
  it('原样照抄的压缩稿，一条损失都不报', () => {
    const a = auditCompression(ORIGINAL, ORIGINAL);
    expect(auditHasLosses(a)).toBe(false);
    expect(a.entriesBefore).toBe(4);
    expect(a.entriesAfter).toBe(4);
  });

  // 用户批注是四带里权威最高的一带。它被删掉而界面不吭声，是这个功能最坏的失败方式。
  it('删掉一条 note: 会被指名道姓地报出来', () => {
    const shrunk = ORIGINAL.replace('    💭 note: 这条是硬要求,别忘了\n', '');
    const a = auditCompression(ORIGINAL, shrunk);
    expect(a.missingNotes).toEqual(['这条是硬要求,别忘了']);
    expect(auditHasLosses(a)).toBe(true);
  });

  it('用户亲手划的高亮丢了也要报', () => {
    const shrunk = ORIGINAL.replace('==2024 年后==', '近几年');
    expect(auditCompression(ORIGINAL, shrunk).missingHighlights).toEqual(['2024 年后']);
  });

  it('用户自己写的那条（💭）被摘要掉了要报', () => {
    const shrunk = ORIGINAL.replace('我的想法:先复现 baseline 再谈改进', '先复现再改进');
    expect(auditCompression(ORIGINAL, shrunk).missingPersonal.length).toBe(1);
  });

  // ⚠️ 2026-08-20 实测抓到的真实一例（宣发那份）。查过库：第 2 块**根本没有批注**，
  // 而压缩稿给它写了一行 `↪ note: AI回复`。这是最坏的一种失败——批注是 💭 那一带，
  // 一行编出来的批注会穿着用户自己的权威被下一个 AI 当成他的主张。
  it('压缩稿凭空多写一行批注，要抓出来', () => {
    const withNote = ORIGINAL.replace(
      '#2 [2025-06-05 06:06 · from Safari]',
      '    ↪ note: AI回复\n#2 [2025-06-05 06:06 · from Safari]',
    );
    const a = auditCompression(ORIGINAL, withNote);
    expect(a.fabricatedNotes).toEqual(['AI回复']);
    expect(auditHasLosses(a)).toBe(true);
  });

  it('原文本来就有的批注，照抄一遍不算编造', () => {
    expect(auditCompression(ORIGINAL, ORIGINAL).fabricatedNotes).toEqual([]);
  });

  // ⚠️ 2026-08-20 差点栽在这上面。原来的实现是拿批注文字去**全文搜**，
  // 于是只要编出来的那句话碰巧在正文里出现过，就会被判成「原文有的」。
  // 批注是结构化的行，就该按行比对。
  it('编的批注碰巧和正文里的字重合，也要抓出来', () => {
    const orig = '#1 [t · from X] 我们讨论了 AI回复 的语气\n#2 [t · from X] 另一段';
    const bad = '#1 [t · from X] 我们讨论了 AI回复 的语气\n    note: AI回复\n#2 [t · from X] 另一段';
    expect(auditCompression(orig, bad).fabricatedNotes).toEqual(['AI回复']);
  });

  // 反过来：那一行本来就在正文里（宣发第 2 块的真实情况），照抄不算编。
  it('原文正文里本来就带着一行批注记号，照抄不算编', () => {
    const orig = '#1 [t · from X] 前半段\n↪ note: AI回复\n后半段';
    expect(auditCompression(orig, orig).fabricatedNotes).toEqual([]);
  });

  it('整节被拆掉要报——第 1 条要求骨架照抄', () => {
    const shrunk = ORIGINAL.replace('## Output Language\n\nAnswer in Chinese.', '');
    expect(auditCompression(ORIGINAL, shrunk).missingSections).toEqual(['Output Language']);
  });

  // 只收拢空白，不做模糊匹配：换行被压掉不算「删了」，改字算。
  it('只是重排了空白不算损失', () => {
    const rewrapped = ORIGINAL.replace('    💭 note: 这条是硬要求,别忘了', '💭 note:  这条是硬要求,别忘了 ');
    expect(auditCompression(ORIGINAL, rewrapped).missingNotes).toEqual([]);
  });
});

// D4-b（2026-08-22）。⚠️ 这一组盯的是一个「改回去测试照样绿」的分类错误：
// 2026-08-22 Ocean 那次跑出来「少了 13 条批注」+「凭空写了 13 条」，数目一样，
// 因为那是同一批东西被改写之后的样子 —— 同一件事报成两条罪，警报翻倍，
// 而最重的那一类（真的凭空捏造）被淹在里面。
describe('改写是第三类，不是「丢了一条」加「编了一条」', () => {
  // ⚠️ 这一对是实测里真的出现过的那一条（申请规划那份）。
  const BEFORE = '现有成绩需按 Fall 2027 开学日复核';
  const AFTER = '需按开学日复核';

  it('删字型的改写配得上对', () => {
    const r = pairRewrites([BEFORE], [AFTER]);
    expect(r.rewrites).toEqual([{ before: BEFORE, after: AFTER }]);
    expect(r.missing).toEqual([]);
    expect(r.fabricated).toEqual([]);
  });

  it('⛔ 两条不相干的批注绝不配对 —— 宁可退回报两条', () => {
    const r = pairRewrites(['这条是硬要求,别忘了'], ['先复现 baseline 再谈改进']);
    expect(r.rewrites).toEqual([]);
    expect(r.missing.length).toBe(1);
    expect(r.fabricated.length).toBe(1);
  });

  it('一条只配一条：两条像的原批注对一条改写，另一条仍然算丢了', () => {
    const r = pairRewrites([BEFORE, '现有成绩需按 Fall 2028 开学日复核'], [AFTER]);
    expect(r.rewrites.length).toBe(1);
    expect(r.missing.length).toBe(1);
  });

  it('整份核对里，改写不再同时算丢和算编', () => {
    const orig = `#1 [t · from X] 正文\n    💭 note: ${BEFORE}`;
    const comp = `#1 [t · from X] 正文\n    💭 note: ${AFTER}`;
    const a = auditCompression(orig, comp);
    expect(a.rewrittenNotes).toEqual([{ before: BEFORE, after: AFTER }]);
    expect(a.missingNotes).toEqual([]);
    expect(a.fabricatedNotes).toEqual([]);
    // ⛔ 但它照样是损失 —— D4-b 改的是分类，不是放松核对。
    expect(auditHasLosses(a)).toBe(true);
  });

  it('长度差得远的删字型改写，重合度撑得住（Dice 撑不住，所以没用 Dice）', () => {
    expect(overlapRatio(BEFORE, AFTER)).toBeGreaterThan(0.6);
  });
});

describe('行级 diff', () => {
  it('把删掉的行标成 cut，保留的标成 same', () => {
    const d = diffLines('a\nb\nc', 'a\nc');
    expect(d.map((x) => x.op)).toEqual(['same', 'cut', 'same']);
  });

  it('模型自己加的行标成 added', () => {
    const d = diffLines('a\nc', 'a\nb\nc');
    expect(d.find((x) => x.op === 'added')?.text).toBe('b');
  });

  // 铺回正文（2026-08-22，Ocean「直接在原文上去划线」）。
  it('原文侧拿到 same+cut，压缩稿侧拿到 same+added', () => {
    const d = diffLines('a\nb\nc', 'a\nx\nc');
    expect(diffChunks(d, 'before', 'a\nb\nc')?.map((c) => [c.op, c.text])).toEqual([
      ['same', 'a'],
      ['cut', 'b'],
      ['same', 'c'],
    ]);
    expect(diffChunks(d, 'after', 'a\nx\nc')?.map((c) => [c.op, c.text])).toEqual([
      ['same', 'a'],
      ['added', 'x'],
      ['same', 'c'],
    ]);
  });

  it('连着的同一种行折成一段', () => {
    const d = diffLines('a\nb\nc\nd', 'a\nd');
    expect(diffChunks(d, 'before', 'a\nb\nc\nd')?.map((c) => c.text)).toEqual(['a', 'b\nc', 'd']);
  });

  it('段之间的空行剪掉，换成下一段头上的 gap', () => {
    const d = diffLines('a\n\nb', 'a');
    const chunks = diffChunks(d, 'before', 'a\n\nb')!;
    expect(chunks.map((c) => [c.text, c.gap])).toEqual([
      ['a', false],
      ['b', true],
    ]);
  });

  it('拼不回原样就返回 null —— ⛔ 缺了行的正文绝不上屏', () => {
    // diffLines 超行数上限时退化成只报原文侧，压缩稿侧的 added 行根本不存在。
    const degraded = diffLines(Array.from({ length: 2600 }, (_, i) => `l${i}`).join('\n'), 'l0\nnew');
    expect(diffChunks(degraded, 'after', 'l0\nnew')).toBeNull();
  });
});

// D-c（2026-08-22）：重跑之后两次的账要加起来。⚠️ 只报第二次那笔，
// 界面上「这一次花了多少」就成了假话 —— 钱是两次都花了的。
describe('两次调用合成一笔账', () => {
  const env = (over: Partial<CompressOutcome>): CompressOutcome => ({
    ok: true,
    text: 'x',
    cuts: null,
    kind: null,
    message: null,
    status: 200,
    inputTokens: 0,
    outputTokens: 0,
    cachedInputTokens: null,
    reasoningTokens: null,
    ms: 0,
    model: 'deepseek-flash',
    ...over,
  });

  it('token 和耗时相加，正文取留下来的那一份', () => {
    const m = mergeOutcomes(
      env({ text: '第一次', inputTokens: 100, outputTokens: 50, ms: 1000 }),
      env({ text: '第二次', inputTokens: 120, outputTokens: 70, ms: 1500 }),
    );
    expect(m.text).toBe('第二次');
    expect(m.inputTokens).toBe(220);
    expect(m.outputTokens).toBe(120);
    expect(m.ms).toBe(2500);
  });

  // ⛔ 有一次没报缓存命中，合起来也算没报 —— 那时候界面写「最多花了」。
  // 编一个偏低的数比说上限更糟。
  it('一次没报缓存命中，合起来就是没报', () => {
    const m = mergeOutcomes(
      env({ cachedInputTokens: 512 }),
      env({ cachedInputTokens: null }),
    );
    expect(m.cachedInputTokens).toBeNull();
  });
});

// D-b（2026-08-22）：闸门的方向被写反过测试照样绿，所以钉一下。
describe('数字硬闸门', () => {
  it('丢了数字就是不够格进库；一个都没丢才放行', () => {
    expect(numbersGateOpen({ missingNumbers: ['2026-11-25'] })).toBe(false);
    expect(numbersGateOpen({ missingNumbers: [] })).toBe(true);
  });
});

describe('算钱', () => {
  it('北京时间 9–12 点、14–18 点是高峰', () => {
    // 北京 10:00 = UTC 02:00
    expect(isPeakBeijing(new Date(Date.UTC(2026, 7, 20, 2, 0)))).toBe(true);
    // 北京 13:00 = UTC 05:00，午休不算高峰
    expect(isPeakBeijing(new Date(Date.UTC(2026, 7, 20, 5, 0)))).toBe(false);
    // 北京 23:00 = UTC 15:00
    expect(isPeakBeijing(new Date(Date.UTC(2026, 7, 20, 15, 0)))).toBe(false);
  });

  it('认不出模型就不报价，而不是编一个', () => {
    expect(priceTier('some-local-model')).toBeNull();
    expect(estimateCost(outcome({ model: 'some-local-model' }))).toBeNull();
  });

  // §6.2 的账：高峰、全未命中，30000 输入 + 2000 输出 = 0.108 元。
  it('高峰全未命中，对得上 §6.2 手算的 0.108 元', () => {
    const c = estimateCost(outcome(), new Date(Date.UTC(2026, 7, 20, 2, 0)));
    expect(c?.peak).toBe(true);
    expect(c?.yuan).toBeCloseTo(0.108, 6);
  });

  // §6.2 的账：高峰、九成命中 = 27000×0.1 + 3000×3 + 2000×9 = 29700/百万 = 0.0297 元。
  // ⚠️ §6.2 那张表里写的是「0.030 元」——那是三位小数的四舍五入，不是另一个数。
  it('高峰九成命中，对得上 §6.2 手算的 0.0297 元', () => {
    const c = estimateCost(
      outcome({ cachedInputTokens: 27_000 }),
      new Date(Date.UTC(2026, 7, 20, 2, 0)),
    );
    expect(c?.yuan).toBeCloseTo(0.0297, 6);
    expect(Number(c!.yuan.toFixed(3))).toBe(0.03);
  });

  // §6.2 的账：闲时全命中，理论下限 0.0105 元。
  it('闲时全命中，对得上 §6.2 手算的 0.0105 元', () => {
    const c = estimateCost(
      outcome({ cachedInputTokens: 30_000 }),
      new Date(Date.UTC(2026, 7, 20, 15, 0)),
    );
    expect(c?.yuan).toBeCloseTo(0.0105, 6);
  });

  // 缺缓存数就往贵了算，并且把「这是上限」这件事标出来。低报会让「一到三分钱」变成假话。
  it('端点没报缓存命中时按全部未命中算，并标明是上限', () => {
    const c = estimateCost(outcome(), new Date(Date.UTC(2026, 7, 20, 2, 0)));
    expect(c?.cacheUnknown).toBe(true);
    expect(c?.yuan).toBeCloseTo(0.108, 6);
  });

  // 一到三分钱这个量级，两位小数会把 0.0105 / 0.0297 全压成同一个数字，
  // 而用户要能拿价目表自己复算。
  it('一分钱上下的金额不会被四舍五入成看不出差别', () => {
    expect(formatYuan(0.0105)).toBe('¥0.0105');
    expect(formatYuan(0.0297)).toBe('¥0.0297');
    expect(formatYuan(0.008)).toBe('¥0.00800');
  });
});

describe('实测记录', () => {
  const base = auditCompression(ORIGINAL, ORIGINAL);

  // 「未报」和「0」在账单上必须能分开 —— §6.2 那个 30 倍全压在这一栏上。
  it('端点没报缓存命中时，记录里写「未报」而不是 0', () => {
    const r = measurementRecord({
      project: '宣发',
      level: 'conservative',
      reasoning: 'low',
      outcome: outcome({ cachedInputTokens: null }),
      audit: base,
      at: new Date(Date.UTC(2026, 7, 20, 2, 0)),
    });
    expect(r).toContain('未报');
    expect(r).not.toMatch(/缓存命中 0\b/);
    expect(r).toContain('北京高峰');
  });

  it('真的一次没命中时，写的是 0', () => {
    const r = measurementRecord({
      project: '宣发',
      level: 'conservative',
      reasoning: '',
      outcome: outcome({ cachedInputTokens: 0 }),
      audit: base,
    });
    expect(r).toContain('缓存命中 0');
    // 断在「缓存」那一行上，不是整段 —— 「其中思考」那行也可能是「未报」，
    // 而那是另一件事。断整段会让这条测试在无关的改动上乱响。
    const cacheLine = r.split('\n').find((l) => l.includes('缓存命中'))!;
    expect(cacheLine).not.toContain('未报');
  });

  // 按次付费时「我以为在用哪档」和「实际在用哪档」差三倍，接口回报的模型名是唯一凭据。
  it('记的是接口回报的模型名', () => {
    const r = measurementRecord({
      project: '申请规划',
      level: 'balanced',
      reasoning: 'medium',
      outcome: outcome({ model: 'deepseek-v4-pro' }),
      audit: base,
    });
    expect(r).toContain('deepseek-v4-pro');
  });

  // 人是「跑一次 → 改设置 → 再跑」这样试的，记录必须记这一次实际用的那份设置。
  it('思考力度进记录，而且「默认」和「关掉」分得开', () => {
    const mk = (reasoning: string) =>
      measurementRecord({ project: 'p', level: 'balanced', reasoning, outcome: outcome(), audit: base });
    expect(mk('')).toContain('默认（没发这个参数）');
    expect(mk('off')).toContain('关掉');
    expect(mk('low')).toContain('low');
  });

  it('一字不改的检查结果也进记录', () => {
    const shrunk = ORIGINAL.replace('    💭 note: 这条是硬要求,别忘了\n', '');
    const r = measurementRecord({
      project: '宣发',
      level: 'aggressive',
      reasoning: 'off',
      outcome: outcome(),
      audit: auditCompression(ORIGINAL, shrunk),
    });
    expect(r).toContain('少1条批注');
  });
});

// ⛔ 回归：2026-08-21 查出来的那两条空核对（见 compress.ts 里 ANY_NOTE_RE 上面那段）。
// 这两条断言钉的不是措辞，是**检测器认不认得渲染器真的打出来的那几个字**。
describe('核对认得真实 pack 打出来的记号', () => {
  // 真实 pack 里的批注行长这样：`💭 note:`（用户写的）和 `ai note:`（AI 写的）。
  // 裸的 `note:` 一条都不存在 —— 旧检测器只认裸的，所以 missingNotes 恒为空。
  const REAL = [
    '## Full Record (chronological)',
    '📌 💭 #7 [2026-08-01 09:00] 我自己写的一条，而且置顶了。',
    '    💭 note: 这条是硬要求',
    '#8 [2026-08-02 10:00 · from Claude] 别人写的一条。',
    '    ai note: 这句是 AI 加的批注',
  ].join('\n');

  it('删掉用户批注会被报出来', () => {
    const cut = REAL.split('\n').filter((l) => !l.includes('💭 note:')).join('\n');
    expect(auditCompression(REAL, cut).missingNotes).toEqual(['这条是硬要求']);
  });

  it('删掉 AI 批注也会被报出来 —— 第 3 条要求的是「所有 note: 行」', () => {
    const cut = REAL.split('\n').filter((l) => !l.includes('ai note:')).join('\n');
    expect(auditCompression(REAL, cut).missingNotes).toEqual(['这句是 AI 加的批注']);
  });

  // 置顶 + 用户自己写的那种块，头上是 `📌 💭 #7`，旧的 `^💭` 匹配不到 ——
  // 恰恰是最重要的那些块漏出了检查。
  it('置顶的用户条目被删掉，也会被报出来', () => {
    const cut = REAL.split('\n').filter((l) => !l.startsWith('📌')).join('\n');
    expect(auditCompression(REAL, cut).missingPersonal).toEqual([
      '我自己写的一条，而且置顶了。',
    ]);
  });
});

// ⛔ 实测（2026-08-21 第二轮）：同一份 pack 的 14 条 `↩` 关系行，第 4 次只剩 2 条、
// 第 7 次一条不剩，**而当时的核对全部报「通过」** —— 旧检查根本没数过这一类。
describe('引用/替代关系掉了要报出来', () => {
  const WITH_LINKS = [
    '## Full Record (chronological)',
    '#7 [2026-08-09 21:07 · from Codex · MCP] 一段结论。',
    '    ↩ cites: [2026-08-07 16:58] # CMU 取舍与落选名单…',
    '    ↩ replaces (that block no longer holds): [2026-08-09 21:07] # MIT MASc…',
  ].join('\n');

  it('少了一条连线 = 没通过', () => {
    const cut = WITH_LINKS.split('\n').filter((l) => !l.includes('replaces')).join('\n');
    const a = auditCompression(WITH_LINKS, cut);
    expect(a.missingRelations).toHaveLength(1);
    expect(auditHasLosses(a)).toBe(true);
  });

  it('连线都在 = 通过', () => {
    expect(auditCompression(WITH_LINKS, WITH_LINKS).missingRelations).toEqual([]);
  });
});

// ⛔ 真实假警报（2026-08-21 第二轮第 6 次）：它把 `“…”` 换成 `"…"`，核对于是报
// 「凭空写了 4 条你没写过的批注」。四条一个字都没改。
// **喊一次狼来了，整个核对就失信了** —— 而「编造批注」是这个界面最重的一句警告。
describe('只换了引号，不算丢也不算编', () => {
  const SRC = ['## Full Record (chronological)', '#1 [t] 正文。', '    ai note: 更正先前“过宽”的结论：要按开学日复核。'].join('\n');
  const SWAPPED = SRC.replace(/[\u201c]/g, '"').replace(/[\u201d]/g, '"');

  it('不报成丢失，也不报成编造', () => {
    const a = auditCompression(SRC, SWAPPED);
    expect(a.missingNotes).toEqual([]);
    expect(a.fabricatedNotes).toEqual([]);
  });

  it('但「一字不改被破了」要单独数出来 —— 两面都真，两面都要说', () => {
    expect(auditCompression(SRC, SWAPPED).quoteRewrites).toBe(1);
    expect(auditHasLosses(auditCompression(SRC, SWAPPED))).toBe(false);
  });

  // ⚠️ 边界不能再宽：真的编一条出来，仍然要被抓住。
  it('真的编一条，照样报', () => {
    const forged = SRC + '\n    ↪ note: 我没写过这句';
    expect(auditCompression(SRC, forged).fabricatedNotes).toEqual(['我没写过这句']);
  });
});

// ⛔⛔ 第二轮实测最重的一条（2026-08-21）：**它一旦真的开始压，就开始丢日期和数字。**
// 91–101% 那几次一个数字都没丢；63% 那次丢了 9 个，含 `2026-11-25`（GRE 最晚重考日）。
// 而这一档的名字就叫「保留结论和数字」。
describe('数字和日期丢了要报出来', () => {
  const SRC = [
    '## Full Record (chronological)',
    '#1 [t · from Codex · MCP] CMU SCS 建议需要重考者最晚 2026-11-25 完成，以留出送分时间。',
    '#2 [t · from Codex · MCP] Fall 2027 scholarship deadline 12-15、final 01-15。TOEFL 104。',
  ].join('\n');

  it('压掉一个截止日期，指名道姓报出来', () => {
    const cut = SRC.replace('，以留出送分时间', '').replace('最晚 2026-11-25 完成', '按时完成');
    const a = auditCompression(SRC, cut);
    expect(a.missingNumbers).toEqual(['2026-11-25']);
    expect(auditHasLosses(a)).toBe(true);
  });

  // ⚠️ 合并重复本来就该让同一个数字少出现几次 —— 比的是出现过没有，不是出现几次。
  it('同一个数字从三处并成一处，不算丢', () => {
    const twice = SRC + '\n#3 [t · from X] 再说一遍 TOEFL 104。';
    expect(auditCompression(twice, SRC).missingNumbers).toEqual([]);
  });

  // ⚠️ PDF 提取出来的文字里 `2026-08-07` 会被拆成 `2026-0 8-0 7`；去空白之后两边才对得上。
  it('从 PDF 里提出来的、带空格的数字也认得', () => {
    const spaced = '#1 [t · from Preview] 最 晚   2026-1 1-2 5 完成。';
    expect(auditCompression(spaced, '#1 [t · from Preview] 最晚 2026-11-25 完成。').missingNumbers).toEqual([]);
  });

  // ⚠️ 千分位：`50,000` 和 `50000` 是同一个数。
  it('千分位逗号不算改动', () => {
    expect(auditCompression('#1 [t] 26,163 / 50,000 字符', '#1 [t] 26163/50000 字符').missingNumbers).toEqual([]);
  });

  // ⚠️ 两位数满篇都是，报出来只会淹掉真正丢掉的那几个。
  it('两位以下的数不进这张单子', () => {
    expect(auditCompression('#1 [t] R29/L24/S25/W26', '#1 [t] 分项略').missingNumbers).toEqual([]);
  });
});
