import { describe, expect, it } from 'vitest';
import { countPackEntries, diffChunks, diffLines, missingNumbersBetween } from './compress';
import {
  addBackNumbers,
  worthRetrying,
  auditEntry,
  compareByEntry,
  entryPercent,
  missingNumberLines,
  splitPackEntries,
} from './compressBlocks';

// 一份最小的 pack，形状和真的一样：小节标题、💭 记号、方括号里的时间和来源、缩进的批注行。
const PACK = `# Project Context: 宣发

Generated by Spool on 2026-08-21. 3 blocks total.

## Pinned Blocks

📌 #1 [2026-08-01 09:00 · from Safari] 报名截止 2026-03-15。
    💭 note: 这条是硬要求

## Full Record (chronological)

#2 [2026-08-20 13:50 · from Claude] 一段很长的引文，里面有 ==划出来的重点== 和别的话。
第二行也属于这一块。
💭 #3 [2026-08-20 14:00] 我自己写的一句。

## Output Language

Answer in Chinese.`;

describe('splitPackEntries', () => {
  it('把 pack 切成条目，记号、时间、来源、正文各归各位', () => {
    const es = splitPackEntries(PACK);
    expect(es.map((e) => e.seq)).toEqual([1, 2, 3]);
    expect(es[0].marks).toEqual(['📌']);
    expect(es[0].section).toBe('Pinned Blocks');
    expect(es[0].source).toBe('Safari');
    expect(es[0].time).toBe('2026-08-01 09:00');
    // 缩进的批注行属于它上面那一块，不是下一块的开头。
    expect(es[0].raw).toContain('note: 这条是硬要求');
    // 没有 `· from` = 用户自己写的，pack 上印的就是 💭。
    expect(es[2].source).toBeNull();
    expect(es[2].marks).toEqual(['💭']);
  });

  it('续行归到它所属的那一块', () => {
    const es = splitPackEntries(PACK);
    expect(es[1].body).toContain('第二行也属于这一块');
    expect(es[2].body).not.toContain('第二行');
  });

  it('小节标题结束一块 —— Output Language 不会被吸进最后一条', () => {
    const es = splitPackEntries(PACK);
    expect(es[2].raw).not.toContain('Answer in Chinese');
  });
});

describe('compareByEntry', () => {
  it('按 #N 配对，一块对一块', () => {
    const c = compareByEntry(PACK, PACK);
    expect(c).not.toBeNull();
    expect(c!.pairs.map((p) => p.seq)).toEqual([1, 2, 3]);
    expect(c!.dropped).toBe(0);
    expect(c!.invented).toBe(0);
    expect(entryPercent(c!.pairs[0])).toBe(100);
  });

  // ⚠️ §9.6.5 点名的那条：模型漏了一块，必须显示「第 N 块在压缩稿里找不到」，不许静默跳过。
  it('压缩稿里少了一块，那一对留着，右边是空的', () => {
    const short = PACK.split('\n').filter((l) => !l.startsWith('💭 #3')).join('\n');
    const c = compareByEntry(PACK, short)!;
    expect(c.dropped).toBe(1);
    const gone = c.pairs.find((p) => p.seq === 3)!;
    expect(gone.before).not.toBeNull();
    expect(gone.after).toBeNull();
  });

  // 反过来也要看得见：它编了一个原文没有的编号。
  it('压缩稿凭空多出来一个编号，也列出来', () => {
    const more = PACK + '\n#9 [2026-08-20 15:00 · from Claude] 原文里没有这一块。';
    const c = compareByEntry(PACK, more)!;
    expect(c.invented).toBe(1);
    expect(c.pairs.find((p) => p.seq === 9)!.before).toBeNull();
  });

  // ⛔ 实测第 7 次撞见的那个：它把整份 pack 原样写了两遍（22 块 → 44 块，剩 194%）。
  // 只按 #N 配对的话这看起来一对不缺，而用户拿到的是一份两倍长的东西。
  it('压缩稿里同一个编号出现两次，单独报出来', () => {
    const twice = PACK + '\n' + PACK;
    const c = compareByEntry(PACK, twice)!;
    expect(c.duplicated).toEqual([1, 2, 3]);
    expect(c.after).toBe(6);
    expect(c.dropped).toBe(0);
    expect(c.invented).toBe(0);
  });

  // ⛔ 置顶的块在 pack 里本来就出现两次（Pinned Blocks 里全文 + Full Record 里一行占位）。
  // 只按 #N 配对会把每一个有置顶块的项目都报成「写了两遍」——实测在〈Flux〉上撞见过。
  it('置顶块的两次出现不算重复', () => {
    const c = compareByEntry(PACK, PACK)!;
    expect(c.duplicated).toEqual([]);
    // 两次出现各自配对：Pinned Blocks 里那一条，和 Full Record 里那一条。
    expect(c.pairs.filter((p) => p.seq === 1)).toHaveLength(1);
    expect(c.pairs[0].section).toBe('Pinned Blocks');
  });

  // 「解析失败必须是一个可见的结果，不是一个异常」——所以返回 null，界面据此退回整份对照。
  it('压缩稿一条都切不出来时返回 null，而不是抛异常', () => {
    expect(compareByEntry(PACK, '模型没照格式写，整段散文。')).toBeNull();
  });
});

// ⛔ 实测撞见的截断（2026-08-21，〈Flux〉#3 是一份 README）：块正文里本来就有二级标题。
describe('正文里的 ## 标题不是小节边界', () => {
  const WITH_MD = [
    '## Full Record (chronological)',
    '#1 [t · from Code] # FLUX',
    '',
    '## 研究线',
    'uv + Python 3.12 可复现环境。',
    '',
    '## 变换层',
    '六种变换。',
    '#2 [t · from Code] 下一块。',
    '## Output Language',
    'Answer in Chinese.',
  ].join('\n');

  it('一块正文里的 ## 归这一块，不截断', () => {
    const es = splitPackEntries(WITH_MD);
    expect(es.map((e) => e.seq)).toEqual([1, 2]);
    expect(es[0].body).toContain('## 研究线');
    expect(es[0].body).toContain('六种变换');
    expect(es[0].section).toBe('Full Record (chronological)');
  });

  it('pack 自己的小节标题照旧是边界', () => {
    const es = splitPackEntries(WITH_MD);
    expect(es[1].raw).not.toContain('Answer in Chinese');
  });
});

// ⛔ 实测撞见的静默丢块（2026-08-21，〈Flux〉#5 是从 Microsoft Word 粘进来的）：
// 那一块的行尾带 `\r`，而 JS 的 `.` 不匹配 `\r`，头行于是解析不出来 —— 旧代码 `continue`
// 掉了它，**不报错、不提示，那一块就是不在核对面上**。
describe('从 Word 粘过来的块（CRLF）不会消失', () => {
  const CRLF = [
    '## Full Record (chronological)',
    '#5 [2026-08-05 15:09 · from Microsoft Word] Experience 2\r',
    'Sound design for a short film.\r',
    '    💭 note: 这段要留着\r',
    '#6 [2026-08-06 14:16 · from Claude · MCP] 下一块。',
  ].join('\n');

  it('照样切得出来', () => {
    expect(splitPackEntries(CRLF).map((e) => e.seq)).toEqual([5, 6]);
  });

  it('批注也认得出来 —— 少了要报', () => {
    const cut = CRLF.split('\n').filter((l) => !l.includes('note:')).join('\n');
    expect(compareByEntry(CRLF, cut)!.pairs[0].audit.missingNotes).toEqual(['这段要留着']);
  });
});

describe('auditEntry', () => {
  it('少掉的批注和高亮，指到具体那一块', () => {
    const [pinned, quoted] = splitPackEntries(PACK);
    expect(auditEntry(pinned, { ...pinned, raw: '📌 #1 [x] 报名截止 2026-03-15。' }).missingNotes)
      .toEqual(['这条是硬要求']);
    expect(auditEntry(quoted, { ...quoted, raw: '#2 [x] 一段引文。' }).missingHighlights)
      .toEqual(['划出来的重点']);
  });

  // 防「添」：压缩稿里的批注行，原文那一块里没有同样的一行。
  it('凭空多写的批注，按块指出来', () => {
    const [pinned] = splitPackEntries(PACK);
    const forged = { ...pinned, raw: pinned.raw + '\n    ↪ note: 我没写过这句' };
    expect(auditEntry(pinned, forged).fabricatedNotes).toEqual(['我没写过这句']);
  });
});

// D7 · 把丢掉的数字加回去（2026-08-22）。
const APPLY = `# Project Context: 申请规划

Generated by Spool on 2026-08-21. 2 blocks total.

## Full Record (chronological)

#1 [2026-08-01 09:00 · from Safari] 第一句话，没有数字。
GRE 最晚重考日是 2026-11-25，别错过。
第三行也没有数字。
#2 [2026-08-02 10:00 · from Claude] 另一块，申请截止 2026-12-15。

## Output Language

Answer in Chinese.`;

const drop = (text: string, starts: string): string =>
  text
    .split('\n')
    .filter((l) => !l.startsWith(starts))
    .join('\n');

describe('addBackNumbers', () => {
  it('丢掉的那一行整行补回来，补完这个数就不缺了', () => {
    const compressed = drop(APPLY, 'GRE');
    expect(missingNumbersBetween(APPLY, compressed)).toContain('2026-11-25');
    const r = addBackNumbers(APPLY, compressed);
    expect(r.added).toContain('2026-11-25');
    expect(r.failed).toEqual([]);
    // ⭐ 插回去的那一行要报出来 —— 界面靠它标「你加回去的」。
    expect(r.lines).toEqual(['GRE 最晚重考日是 2026-11-25，别错过。']);
    expect(r.text).toContain('GRE 最晚重考日是 2026-11-25，别错过。');
    // ⭐ 闸门要真的能过 —— 补回去而闸门还关着，等于白补。
    expect(missingNumbersBetween(APPLY, r.text)).toEqual([]);
  });

  it('插在它前面最后一个还活着的行后面，⛔ 不会跑到别的块里去', () => {
    const compressed = drop(APPLY, 'GRE');
    const lines = addBackNumbers(APPLY, compressed).text.split('\n');
    const at = lines.findIndex((l) => l.startsWith('GRE'));
    expect(lines[at - 1]).toContain('#1 [2026-08-01');
    expect(lines[at + 1]).toBe('第三行也没有数字。');
  });

  // ⭐ 2026-08-22（Ocean：「文本无法插回去了，如果插不回去就添加一个文本更正，把原文更正回去」）。
  // ⚠️ 这两条以前断言的是「一个字不动，如实报 failed」—— 那是**旧的**做法：让用户再花一次钱
  // 重压一遍，而那一行原文就在手边。现在改成按小节更正回去。⛔ 别把它们改回去。
  it('整块不见了 —— 把那一整条原文放回原来的位置，⛔ 不是接一条裸行', () => {
    const compressed = drop(APPLY, '#2 ');
    const r = addBackNumbers(APPLY, compressed);
    expect(r.added).toContain('2026-12-15');
    expect(r.failed).toEqual([]);
    // ⭐ 放回去的是**整条**，所以块数回到原文那个数（不是压缩稿那个数）。
    // ⛔ 只接带数字的那一行的话，`splitPackEntries` 会把它算成**上一块的正文** ——
    //    核对面上那一块会凭空长出一句不属于它的话。
    expect(countPackEntries(r.text)).toBe(countPackEntries(APPLY));
    expect(compareByEntry(APPLY, r.text)!.dropped).toBe(0);
    // ⚠️ 它自己就是一张块卡片，看得见 —— 所以不算「不在块里的那几行」。
    expect(r.outsideBlocks).toBe(0);
    // 补完闸门就过得了 —— 补回去而闸门还关着，等于白补。
    expect(missingNumbersBetween(APPLY, r.text)).toEqual([]);
  });

  it('不属于任何一块的行（附件正文那种）接在它那一节的末尾', () => {
    const withFiles = APPLY.replace(
      '## Output Language',
      '## Related Files & Links\n\n- 方案.pdf (pdf)\n      第 1 页 · 目标分数 325–328\n\n## Output Language',
    );
    const compressed = drop(withFiles, '      第 1 页');
    const r = addBackNumbers(withFiles, compressed);
    expect(r.added).toContain('325');
    expect(r.outsideBlocks).toBe(1);
    // 接在它自己那一节里，⛔ 不许跑到 Output Language 后面去。
    const at = r.text.split('\n');
    expect(at.indexOf('      第 1 页 · 目标分数 325–328')).toBeGreaterThan(
      at.indexOf('## Related Files & Links'),
    );
    expect(at.indexOf('      第 1 页 · 目标分数 325–328')).toBeLessThan(
      at.indexOf('## Output Language'),
    );
    // 块数一个都不许多。
    expect(countPackEntries(r.text)).toBe(countPackEntries(compressed));
  });

  it('整份切不出块 —— 连小节标题一起补在末尾，⛔ 不许裸接在最后一块后面', () => {
    const r = addBackNumbers(APPLY, '模型没照格式写，就一句话。');
    expect(r.added.length).toBeGreaterThan(0);
    expect(r.failed).toEqual([]);
    // 压缩稿里根本没有这一节，所以标题跟着补上 —— 不补的话这几行会被算成上一块的正文。
    expect(r.text).toContain('## Full Record (chronological)');
    expect(r.text).toContain('GRE 最晚重考日是 2026-11-25，别错过。');
  });

  // ⛔ Spool 自己印上去的那两类行不算用户的字。截断标记里那个数是渲染器算出来的字数，
  //    被算成「丢了一个数字」的话，数字硬闸门会把一份好稿子挡在库外，而且补不回来。
  it('截断标记里的字数不算丢失的数字', () => {
    const withMarker = APPLY.replace(
      '第三行也没有数字。',
      '第三行也没有数字。\n[... truncated, 8945 more chars not shown ...]',
    );
    expect(missingNumbersBetween(withMarker, APPLY)).toEqual([]);
  });

  // ⭐ 补回去的那一行**不许在核对界面上被说成「它新写的」** —— 那句话会把责任安到模型头上，
  // 而这一行恰恰是用户自己原文里的原话。LCS 会把它和原文那一行对齐，于是它是 same。
  it('补回去的那一行在核对界面上不算「它新写的」', () => {
    const compressed = drop(APPLY, 'GRE');
    const r = addBackNumbers(APPLY, compressed);
    const pair = compareByEntry(APPLY, r.text)!.pairs.find((p) => p.seq === 1)!;
    const after = diffChunks(
      diffLines(pair.before!.body, pair.after!.body),
      'after',
      pair.after!.body,
    )!;
    expect(after.every((c) => c.op !== 'added')).toBe(true);
  });

  it('⛔ 不补 ↩ 那种预览行 —— 它是别的块被截断的开头', () => {
    const withRel = APPLY.replace(
      '第三行也没有数字。',
      '第三行也没有数字。\n↩ cites: #9（2026-07-04 那份…',
    );
    const r = addBackNumbers(withRel, drop(withRel, '↩'));
    expect(r.text).not.toContain('↩ cites:');
  });
});


// D-c（2026-08-22）：坏结果自动重跑一次。⚠️ 判据必须是结构性的 ——
// 「质量不够好」那种要人判断的话不能进这里，否则它会替用户花第二笔钱。
describe('worthRetrying', () => {
  it('一模一样地压回来（剩 100%）算坏结果 —— 钱花了，什么也没发生', () => {
    expect(worthRetrying(APPLY, APPLY)).toBe(true);
  });

  it('切不出块算坏结果', () => {
    expect(worthRetrying(APPLY, '模型没照格式写。')).toBe(true);
  });

  it('块数对不上算坏结果', () => {
    expect(worthRetrying(APPLY, drop(APPLY, '#2 '))).toBe(true);
  });

  // ⛔ 丢数字**不在**判据里：那一类有「从原文加回去」补，不该再花第二笔钱。
  it('只是丢了个数字不算 —— 那一类是补，不是重跑', () => {
    const shorter = APPLY.replace('GRE 最晚重考日是 2026-11-25，别错过。', '短。')
      .replace('第一句话，没有数字。', '短。')
      .replace('第三行也没有数字。', '短。');
    expect(worthRetrying(APPLY, shorter)).toBe(false);
  });
});


// ⭐ Ocean 2026-08-22 第二轮第 3 条:「根本看不到丢掉的数字是哪一块的,即使文字说 #2,
// 我也不知道 #2 写了什么,需要指到文字内容上去」。
describe('missingNumberLines', () => {
  it('指到原文那一行，而且和「加回去」补的是同一行', () => {
    const compressed = drop(APPLY, 'GRE');
    const pair = compareByEntry(APPLY, compressed)!.pairs.find((p) => p.seq === 1)!;
    const shown = missingNumberLines(pair.before!, pair.after!, pair.audit.missingNumbers);
    expect(shown).toEqual([
      { line: 'GRE 最晚重考日是 2026-11-25，别错过。', numbers: ['2026-11-25'] },
    ]);
    expect(addBackNumbers(APPLY, compressed).lines).toEqual([shown[0].line]);
  });

  it('只补点中的那一个，别的不动', () => {
    const compressed = drop(drop(APPLY, 'GRE'), '#2 ');
    const r = addBackNumbers(APPLY, compressed, ['2026-11-25']);
    expect(r.added).toEqual(['2026-11-25']);
    expect(r.lines).toHaveLength(1);
  });
});
