import { describe, expect, it } from 'vitest';
import {
  auditCompression,
  auditHasLosses,
  countPackEntries,
  diffLines,
  estimateCost,
  formatYuan,
  isPeakBeijing,
  measurementRecord,
  priceTier,
  type CompressOutcome,
} from './compress';

const ORIGINAL = `# Project Context: 机器学习课

Generated by Spool on 2026-08-20. 4 blocks total.

## How to Read This Context

四带说明……

## Full Record (chronological)

📌 #1 [2025-05-06 15:00 · from Claude] 一直没懂为什么要除 sqrt(d_k)
#2 [2025-06-05 06:06 · from Safari] 课程要求:期末项目要复现一篇 ==2024 年后== 的论文
    note: 这条是硬要求,别忘了
💭 #3 [2025-06-15 15:06] 我的想法:先复现 baseline 再谈改进
#4 [2025-06-15 15:16 · from Claude] 结论:除以 sqrt(d_k) 控制点积方差

## Output Language

Answer in Chinese.`;

const outcome = (over: Partial<CompressOutcome> = {}): CompressOutcome => ({
  ok: true,
  text: '',
  cuts: null,
  kind: null,
  message: null,
  status: null,
  inputTokens: 30_000,
  outputTokens: 2_000,
  cachedInputTokens: null,
  reasoningTokens: null,
  ms: 8_000,
  model: 'deepseek-v4-flash',
  ...over,
});

describe('数块', () => {
  it('数的是条目行，不是所有行', () => {
    expect(countPackEntries(ORIGINAL)).toBe(4);
  });

  it('📌 和 💭 前缀不影响计数', () => {
    expect(countPackEntries('📌 #1 [a] x\n💭 #2 [b] y\n#3 [c] z')).toBe(3);
  });
});

describe('核对：不该删的删了没有', () => {
  it('原样照抄的压缩稿，一条损失都不报', () => {
    const a = auditCompression(ORIGINAL, ORIGINAL);
    expect(auditHasLosses(a)).toBe(false);
    expect(a.entriesBefore).toBe(4);
    expect(a.entriesAfter).toBe(4);
  });

  // 用户批注是四带里权威最高的一带。它被删掉而界面不吭声，是这个功能最坏的失败方式。
  it('删掉一条 note: 会被指名道姓地报出来', () => {
    const shrunk = ORIGINAL.replace('    note: 这条是硬要求,别忘了\n', '');
    const a = auditCompression(ORIGINAL, shrunk);
    expect(a.missingNotes).toEqual(['这条是硬要求,别忘了']);
    expect(auditHasLosses(a)).toBe(true);
  });

  it('用户亲手划的高亮丢了也要报', () => {
    const shrunk = ORIGINAL.replace('==2024 年后==', '近几年');
    expect(auditCompression(ORIGINAL, shrunk).missingHighlights).toEqual(['2024 年后']);
  });

  it('用户自己写的那条（💭）被摘要掉了要报', () => {
    const shrunk = ORIGINAL.replace('我的想法:先复现 baseline 再谈改进', '先复现再改进');
    expect(auditCompression(ORIGINAL, shrunk).missingPersonal.length).toBe(1);
  });

  // ⚠️ 2026-08-20 实测抓到的真实一例（宣发那份）。查过库：第 2 块**根本没有批注**，
  // 而压缩稿给它写了一行 `↪ note: AI回复`。这是最坏的一种失败——批注是 💭 那一带，
  // 一行编出来的批注会穿着用户自己的权威被下一个 AI 当成他的主张。
  it('压缩稿凭空多写一行批注，要抓出来', () => {
    const withNote = ORIGINAL.replace(
      '#2 [2025-06-05 06:06 · from Safari]',
      '    ↪ note: AI回复\n#2 [2025-06-05 06:06 · from Safari]',
    );
    const a = auditCompression(ORIGINAL, withNote);
    expect(a.fabricatedNotes).toEqual(['AI回复']);
    expect(auditHasLosses(a)).toBe(true);
  });

  it('原文本来就有的批注，照抄一遍不算编造', () => {
    expect(auditCompression(ORIGINAL, ORIGINAL).fabricatedNotes).toEqual([]);
  });

  // ⚠️ 2026-08-20 差点栽在这上面。原来的实现是拿批注文字去**全文搜**，
  // 于是只要编出来的那句话碰巧在正文里出现过，就会被判成「原文有的」。
  // 批注是结构化的行，就该按行比对。
  it('编的批注碰巧和正文里的字重合，也要抓出来', () => {
    const orig = '#1 [t · from X] 我们讨论了 AI回复 的语气\n#2 [t · from X] 另一段';
    const bad = '#1 [t · from X] 我们讨论了 AI回复 的语气\n    note: AI回复\n#2 [t · from X] 另一段';
    expect(auditCompression(orig, bad).fabricatedNotes).toEqual(['AI回复']);
  });

  // 反过来：那一行本来就在正文里（宣发第 2 块的真实情况），照抄不算编。
  it('原文正文里本来就带着一行批注记号，照抄不算编', () => {
    const orig = '#1 [t · from X] 前半段\n↪ note: AI回复\n后半段';
    expect(auditCompression(orig, orig).fabricatedNotes).toEqual([]);
  });

  it('整节被拆掉要报——第 1 条要求骨架照抄', () => {
    const shrunk = ORIGINAL.replace('## Output Language\n\nAnswer in Chinese.', '');
    expect(auditCompression(ORIGINAL, shrunk).missingSections).toEqual(['Output Language']);
  });

  // 只收拢空白，不做模糊匹配：换行被压掉不算「删了」，改字算。
  it('只是重排了空白不算损失', () => {
    const rewrapped = ORIGINAL.replace('    note: 这条是硬要求,别忘了', 'note:  这条是硬要求,别忘了 ');
    expect(auditCompression(ORIGINAL, rewrapped).missingNotes).toEqual([]);
  });
});

describe('行级 diff', () => {
  it('把删掉的行标成 cut，保留的标成 same', () => {
    const d = diffLines('a\nb\nc', 'a\nc');
    expect(d.map((x) => x.op)).toEqual(['same', 'cut', 'same']);
  });

  it('模型自己加的行标成 added', () => {
    const d = diffLines('a\nc', 'a\nb\nc');
    expect(d.find((x) => x.op === 'added')?.text).toBe('b');
  });
});

describe('算钱', () => {
  it('北京时间 9–12 点、14–18 点是高峰', () => {
    // 北京 10:00 = UTC 02:00
    expect(isPeakBeijing(new Date(Date.UTC(2026, 7, 20, 2, 0)))).toBe(true);
    // 北京 13:00 = UTC 05:00，午休不算高峰
    expect(isPeakBeijing(new Date(Date.UTC(2026, 7, 20, 5, 0)))).toBe(false);
    // 北京 23:00 = UTC 15:00
    expect(isPeakBeijing(new Date(Date.UTC(2026, 7, 20, 15, 0)))).toBe(false);
  });

  it('认不出模型就不报价，而不是编一个', () => {
    expect(priceTier('some-local-model')).toBeNull();
    expect(estimateCost(outcome({ model: 'some-local-model' }))).toBeNull();
  });

  // §6.2 的账：高峰、全未命中，30000 输入 + 2000 输出 = 0.108 元。
  it('高峰全未命中，对得上 §6.2 手算的 0.108 元', () => {
    const c = estimateCost(outcome(), new Date(Date.UTC(2026, 7, 20, 2, 0)));
    expect(c?.peak).toBe(true);
    expect(c?.yuan).toBeCloseTo(0.108, 6);
  });

  // §6.2 的账：高峰、九成命中 = 27000×0.1 + 3000×3 + 2000×9 = 29700/百万 = 0.0297 元。
  // ⚠️ §6.2 那张表里写的是「0.030 元」——那是三位小数的四舍五入，不是另一个数。
  it('高峰九成命中，对得上 §6.2 手算的 0.0297 元', () => {
    const c = estimateCost(
      outcome({ cachedInputTokens: 27_000 }),
      new Date(Date.UTC(2026, 7, 20, 2, 0)),
    );
    expect(c?.yuan).toBeCloseTo(0.0297, 6);
    expect(Number(c!.yuan.toFixed(3))).toBe(0.03);
  });

  // §6.2 的账：闲时全命中，理论下限 0.0105 元。
  it('闲时全命中，对得上 §6.2 手算的 0.0105 元', () => {
    const c = estimateCost(
      outcome({ cachedInputTokens: 30_000 }),
      new Date(Date.UTC(2026, 7, 20, 15, 0)),
    );
    expect(c?.yuan).toBeCloseTo(0.0105, 6);
  });

  // 缺缓存数就往贵了算，并且把「这是上限」这件事标出来。低报会让「一到三分钱」变成假话。
  it('端点没报缓存命中时按全部未命中算，并标明是上限', () => {
    const c = estimateCost(outcome(), new Date(Date.UTC(2026, 7, 20, 2, 0)));
    expect(c?.cacheUnknown).toBe(true);
    expect(c?.yuan).toBeCloseTo(0.108, 6);
  });

  // 一到三分钱这个量级，两位小数会把 0.0105 / 0.0297 全压成同一个数字，
  // 而用户要能拿价目表自己复算。
  it('一分钱上下的金额不会被四舍五入成看不出差别', () => {
    expect(formatYuan(0.0105)).toBe('¥0.0105');
    expect(formatYuan(0.0297)).toBe('¥0.0297');
    expect(formatYuan(0.008)).toBe('¥0.00800');
  });
});

describe('实测记录', () => {
  const base = auditCompression(ORIGINAL, ORIGINAL);

  // 「未报」和「0」在账单上必须能分开 —— §6.2 那个 30 倍全压在这一栏上。
  it('端点没报缓存命中时，记录里写「未报」而不是 0', () => {
    const r = measurementRecord({
      project: '宣发',
      level: 'conservative',
      outcome: outcome({ cachedInputTokens: null }),
      audit: base,
      at: new Date(Date.UTC(2026, 7, 20, 2, 0)),
    });
    expect(r).toContain('未报');
    expect(r).not.toMatch(/缓存命中 0\b/);
    expect(r).toContain('北京高峰');
  });

  it('真的一次没命中时，写的是 0', () => {
    const r = measurementRecord({
      project: '宣发',
      level: 'conservative',
      outcome: outcome({ cachedInputTokens: 0 }),
      audit: base,
    });
    expect(r).toContain('缓存命中 0');
    // 断在「缓存」那一行上，不是整段 —— 「其中思考」那行也可能是「未报」，
    // 而那是另一件事。断整段会让这条测试在无关的改动上乱响。
    const cacheLine = r.split('\n').find((l) => l.includes('缓存命中'))!;
    expect(cacheLine).not.toContain('未报');
  });

  // 按次付费时「我以为在用哪档」和「实际在用哪档」差三倍，接口回报的模型名是唯一凭据。
  it('记的是接口回报的模型名', () => {
    const r = measurementRecord({
      project: '申请规划',
      level: 'balanced',
      outcome: outcome({ model: 'deepseek-v4-pro' }),
      audit: base,
    });
    expect(r).toContain('deepseek-v4-pro');
  });

  it('一字不改的检查结果也进记录', () => {
    const shrunk = ORIGINAL.replace('    note: 这条是硬要求,别忘了\n', '');
    const r = measurementRecord({
      project: '宣发',
      level: 'aggressive',
      outcome: outcome(),
      audit: auditCompression(ORIGINAL, shrunk),
    });
    expect(r).toContain('少1条批注');
  });
});
