import { describe, expect, it } from 'vitest';
import { auditCompression, auditHasLosses } from './compress';
import { isEmptyHeld, shieldPack, unshieldPack } from './shield';

// R5（2026-08-22，Ocean 第二轮第 5 条）：**批注根本不发给 AI。**
// 这一整组测试盯的是同一句话：**摘下来的东西，模型看不见；放回去之后，一个字都没变。**

const PACK = `# Project Context: 申请规划

Generated by Spool on 2026-08-21. 2 blocks total.

## Full Record (chronological)

#1 [2026-08-01 09:00 · from Safari] GRE 最晚重考日是 2026-11-25。这里还有一句==划了重点的话==。
    💭 note: 别把 WES 3.87 写进申请。
    ↩ cites: [2026-07-30 08:00] 另一块的开头几十个字…
#2 [2026-08-02 10:00 · from Claude] 另一块，申请截止 2026-12-15。
    ai note: 这条是 AI 写的批注。

## Output Language

Answer in Chinese.`;

describe('摘掉不该给 AI 看的东西', () => {
  it('批注行、关系行、高亮原文，一个字都不进送出去的那一份', () => {
    const { text, held } = shieldPack(PACK);
    expect(text).not.toContain('别把 WES 3.87 写进申请');
    expect(text).not.toContain('这条是 AI 写的批注');
    expect(text).not.toContain('↩ cites:');
    expect(text).not.toContain('划了重点的话');
    // 正文照常送出去 —— ⛔ 摘的是批注，不是内容。
    expect(text).toContain('GRE 最晚重考日是 2026-11-25');
    expect(text).toContain('申请截止 2026-12-15');
    // 高亮换成占位符，位子还占着。
    expect(text).toContain('⟦H0⟧');
    expect(held.spans).toEqual(['==划了重点的话==']);
    expect(held.byEntry.map((h) => h.key)).toEqual([
      'Full Record (chronological)#1',
      'Full Record (chronological)#2',
    ]);
  });

  it('原样送回来 = 原样放回去，一个字不差', () => {
    const { text, held } = shieldPack(PACK);
    const back = unshieldPack(text, held);
    expect(back.text).toBe(PACK);
    expect(back.orphaned).toEqual([]);
    expect(back.lostSpans).toEqual([]);
  });

  // ⭐ 这一条是整件事的正题：**模型把正文改烂了，批注照样一个字不动。**
  it('模型把正文整段改写了，批注和关系行照样原样回到它自己那一块', () => {
    const { text, held } = shieldPack(PACK);
    const mangled = text
      .replace(/GRE 最晚重考日是 2026-11-25。这里还有一句⟦H0⟧。/, 'GRE 重考日 2026-11-25，另有一句⟦H0⟧。')
      .replace('另一块，申请截止 2026-12-15。', '截止 2026-12-15。');
    const back = unshieldPack(mangled, held);
    expect(back.text).toContain('    💭 note: 别把 WES 3.87 写进申请。');
    expect(back.text).toContain('    ai note: 这条是 AI 写的批注。');
    expect(back.text).toContain('    ↩ cites: [2026-07-30 08:00] 另一块的开头几十个字…');
    expect(back.text).toContain('==划了重点的话==');
    expect(back.orphaned).toEqual([]);
    // ⭐ 而核对面上那五类警告一条都不会响 —— 这就是「结构上做不到」。
    expect(auditHasLosses(auditCompression(PACK, back.text))).toBe(false);
  });

  it('批注回的是它自己那一块，⛔ 不许串到别的块上', () => {
    const { text, held } = shieldPack(PACK);
    const back = unshieldPack(text, held).text.split('\n');
    const at = back.findIndex((l) => l.includes('别把 WES 3.87'));
    // #1 的批注必须落在 #1 和 #2 之间。
    expect(back.findIndex((l) => l.startsWith('#1 '))).toBeLessThan(at);
    expect(at).toBeLessThan(back.findIndex((l) => l.startsWith('#2 ')));
  });

  // ⛔ 放回失败必须报出来。静默丢掉一条批注，正是这一整条改动本来要根除的那件事。
  it('那一块整个不见了 —— 它的批注报成 orphaned，不许静默丢掉', () => {
    const { text, held } = shieldPack(PACK);
    const dropped = text
      .split('\n')
      .filter((l) => !l.startsWith('#2 '))
      .join('\n');
    const back = unshieldPack(dropped, held);
    expect(back.orphaned.map((h) => h.key)).toEqual(['Full Record (chronological)#2']);
    expect(back.text).not.toContain('这条是 AI 写的批注');
  });

  it('占位符被模型吃掉了 —— 报成 lostSpans，⛔ 不许硬塞回一句话里', () => {
    const { text, held } = shieldPack(PACK);
    const back = unshieldPack(text.replace('⟦H0⟧', ''), held);
    expect(back.lostSpans).toEqual(['==划了重点的话==']);
    expect(back.text).not.toContain('划了重点的话');
  });

  it('本来就没有批注/高亮的 pack 整条路可以跳过', () => {
    const plain = '# Project Context: X\n\n## Full Record (chronological)\n\n#1 [2026-08-01] 一句话。';
    expect(isEmptyHeld(shieldPack(plain).held)).toBe(true);
    expect(shieldPack(plain).text).toBe(plain);
  });

  // ⚠️ 从 Word 粘进来的块带 CRLF。`packLines` 是**故意**把 `\r` 剪掉的（compress.ts 上有
  // 一整段讲这件事），所以放回去之后 `\r` 不在了 —— 这是已知代价，不是漏掉的。
  // ⛔ 核对那一路的每一个判断都先 `norm`（空白折叠），所以它不会变成假警报。
  it('从 Word 粘来的 CRLF 会被剪掉，除此之外一字不差', () => {
    const crlf = PACK.split('\n').join('\r\n');
    const { text, held } = shieldPack(crlf);
    expect(unshieldPack(text, held).text).toBe(PACK);
  });

  // ⚠️ 块外面出现的 `note:`（附件正文里抄了一句）没有块可以放回去 —— 摘了就再也放不回原位。
  it('块外面的 note: 不摘，照旧送出去', () => {
    const withStray = PACK.replace(
      '## Output Language',
      '## Related Files & Links\n\n- 方案.pdf (pdf)\n      note: 这是 PDF 正文里抄到的一句\n\n## Output Language',
    );
    const { text } = shieldPack(withStray);
    expect(text).toContain('note: 这是 PDF 正文里抄到的一句');
  });
});
